### ISSUE TITLE
Time to archive the project?

### ISSUE THREAD

**Issue by talentlessguy** [keroxp/dlink#36]
With Deno 1.8 import maps got stabilized (see: https://github.com/denoland/deno/pull/9526) looks like dlink isn't required anymore.

Example from [Manual](https://deno.land/manual/linking_to_external_code/import_maps):

```json
{
   "imports": {
      "fmt/": "https://deno.land/std@0.90.0/fmt/"
   }
}
```

I am not sure if it's a bad idea to archive the project but it makes sense when such functionality is already present in the Deno itself.

**Comment by keroxp** [comment]
No plan to archive. Use or not is all up to you.
